version: "3.9"

services:
  djangoapp:
    container_name: djangoapp
    build: .
    entrypoint:
      - /app/run.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=root
      - PG_DB=sample_demo
      - PG_PORT=5432
      - PG_HOST=db
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis

  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_DB=sample_demo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  celery:
    build: .
    entrypoint:
      - /app/celery-run.sh
    volumes:
      - .:/app
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - djangoapp
      - redis
  
  redis:
    image: "redis:alpine"

volumes:
  pgdata: {}